-- theme.lua — one command re-skins the whole desktop.
--
-- Omarchy's signature trick: pick a theme and Ghostty, JankyBorders,
-- SketchyBar, the shell prompt, bat, btop, k9s, Neovim, the wallpaper and every
-- Hammerspoon panel (menu / OSD / which-key / clipboard) all change together.
--
-- The catalogue is `palettes.lua`. This file converts each palette into the
-- shape every target wants and applies it, then remembers the choice in
-- `hs.settings` so `init.lua` can re-assert it on login.
--
--   require("theme").set("nord")        -- apply + persist + toast
--   require("theme").cycle(1)           -- next theme  (Ctrl+Alt+Space)
--   require("theme").current()          -- active palette table
--   require("theme").onChange(fn)       -- fn(palette) on every change
--
-- Targets that reload live: Hammerspoon UI, JankyBorders, SketchyBar, Ghostty,
-- wallpaper, macOS light/dark. Targets that need a fresh process: bat, btop,
-- k9s, Neovim, the shell prompt (open a new window / `exec zsh`).

local settings = require("hs.settings")
local palettes = require("palettes")

local M = {}
local HOME = os.getenv("HOME")
local KEY  = "omachy.theme"
local log  = hs.logger.new("theme", "info")

M.themes = palettes
M.setAppearance = true       -- also flip macOS light/dark to match the theme
M.setWallpaper  = true       -- also set the palette's wallpaper if it exists

-- ── helpers ────────────────────────────────────────────────────────────────
local function byName(name)
  for _, p in ipairs(palettes) do if p.name == name then return p end end
end

-- "#rrggbb" -> "0xAArrggbb"  (AA defaults to ff / opaque)
local function bar(hex, aa)
  return "0x" .. (aa or "ff") .. hex:gsub("#", ""):lower()
end

local function writeFile(path, body)
  path = path:gsub("^~", HOME)
  hs.execute(("mkdir -p %q"):format(path:match("^(.*)/[^/]*$")))
  local f, err = io.open(path, "w")
  if not f then log.ef("write %s: %s", path, err); return false end
  f:write(body); f:close()
  return true
end

local function readFile(path)
  local f = io.open((path:gsub("^~", HOME)), "r")
  if not f then return nil end
  local s = f:read("*a"); f:close(); return s
end

-- run a shell command async, log non-zero exits. GUI-launched Hammerspoon has
-- a bare PATH, so prepend Homebrew's bin for `sketchybar` / `borders` / etc.
local function sh(cmd)
  hs.task.new("/bin/sh", function(rc, _, se)
    if rc ~= 0 then log.wf("`%s` exited %d %s", cmd, rc, (se or ""):gsub("%s+$", "")) end
  end, { "-c", "export PATH=/opt/homebrew/bin:/usr/bin:/bin:$PATH; " .. cmd }):start()
end

-- ── per-target appliers ────────────────────────────────────────────────────

-- JankyBorders: update the running daemon now, and drop a theme.sh that
-- bordersrc sources so a daemon restart keeps the colour.
local function applyBorders(p)
  local active   = ("glow(%s)"):format(bar(p.accent))
  local inactive = bar(p.surface)
  writeFile("~/.config/borders/theme.sh", ("# generated by hammerspoon/theme.lua — %s\n"):format(p.name)
    .. ("active_color=\"%s\"\n"):format(active)
    .. ("inactive_color=\"%s\"\n"):format(inactive))
  sh(("borders active_color=%q inactive_color=%q"):format(active, inactive))
end

-- SketchyBar: theme.sh of exported 0x colours, sourced by sketchybarrc.
local function applySketchybar(p)
  local body = ([[# generated by hammerspoon/theme.lua — %s
export BAR_BG=%s
export BAR_EXTERNAL=%s
export BAR_ISLAND=%s
export BAR_BORDER=%s
export BAR_ACCENT=%s
export BAR_ACCENT_DIM=%s
export BAR_ACCENT_B=%s
export BAR_TEXT=%s
export BAR_SUBTEXT=%s
export BAR_SURFACE=%s
export BAR_RED=%s
export BAR_GREEN=%s
export BAR_YELLOW=%s
export BAR_BLUE=%s
]]):format(p.name,
    bar(p.base, "f0"), bar(p.base, "cc"), bar(p.mantle, "f0"), bar(p.accent),
    bar(p.accent), bar(p.accent, "1a"), bar(p.accent, "40"),
    bar(p.text), bar(p.subtext), bar(p.surface),
    bar(p.red), bar(p.green), bar(p.yellow), bar(p.blue))
  writeFile("~/.config/sketchybar/theme.sh", body)
  sh("sketchybar --reload")
end

-- Ghostty: theme.conf (last include in config wins) + reload the running app.
local function applyGhostty(p)
  writeFile("~/.config/ghostty/theme.conf",
    ("# generated by hammerspoon/theme.lua — do not edit\ntheme = %s\n"):format(p.ghostty))
  local app = hs.application.get("com.mitchellh.ghostty")
  if not app then return end
  if not app:selectMenuItem("Reload Configuration")
     and not app:selectMenuItem({ "Ghostty", "Reload Configuration" }) then
    sh("/usr/bin/pkill -USR2 -x ghostty")   -- best effort; harmless if unsupported
  end
end

-- bat: validate the requested theme against the installed set, fall back sanely.
local function applyBat(p)
  hs.task.new("/opt/homebrew/bin/bat", function(_, out)
    local want, ok = p.bat, false
    for line in (out or ""):gmatch("[^\n]+") do if line == want then ok = true break end end
    if not ok then want = p.dark and "ansi" or "GitHub" end
    writeFile("~/.config/bat/config", ('--theme="%s"\n--paging=never\n'):format(want))
  end, { "--list-themes" }):start()
end

-- starship: two shapes of config in the wild —
--   * palette-based (repo's config/starship.toml): flip the `palette = '...'` line
--   * our minimal "Omachy Starship prompt" config: regenerate from a template
--     so it re-themes deterministically (and reversibly)
local STARSHIP_TEMPLATE = [[# Omachy Starship prompt — %s (managed by hammerspoon/theme.lua)

format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "bold %s"
truncation_length = 3

[git_branch]
symbol = " "
style = "bold %s"

[git_status]
style = "bold %s"

[character]
success_symbol = "[❯](bold %s)"
error_symbol = "[❯](bold %s)"
]]

local function applyStarship(p)
  local path = HOME .. "/.config/starship.toml"
  local body = readFile(path)
  if not body then return end
  local new
  if body:find("palette = '") then
    new = body:gsub("palette = '[%w_]+'", ("palette = '%s'"):format(p.starship), 1)
  elseif body:find("Omachy Starship prompt", 1, true) then
    new = STARSHIP_TEMPLATE:format(p.label, p.blue, p.green, p.yellow, p.accent, p.red)
  else
    return   -- unknown custom config: leave it alone
  end
  if new ~= body then writeFile(path, new) end
end

-- btop: a generated theme file + point btop.conf at it (created if absent).
local function applyBtop(p)
  local t = ([[# generated by hammerspoon/theme.lua — %s
theme[main_bg]="%s"
theme[main_fg]="%s"
theme[title]="%s"
theme[hi_fg]="%s"
theme[selected_bg]="%s"
theme[selected_fg]="%s"
theme[inactive_fg]="%s"
theme[graph_text]="%s"
theme[meter_bg]="%s"
theme[proc_misc]="%s"
theme[cpu_box]="%s"
theme[mem_box]="%s"
theme[net_box]="%s"
theme[proc_box]="%s"
theme[div_line]="%s"
theme[temp_start]="%s"
theme[temp_mid]="%s"
theme[temp_end]="%s"
theme[cpu_start]="%s"
theme[cpu_mid]="%s"
theme[cpu_end]="%s"
theme[free_start]="%s"
theme[free_mid]="%s"
theme[free_end]="%s"
theme[download_start]="%s"
theme[upload_start]="%s"
]]):format(p.name, p.base, p.text, p.text, p.accent, p.surface, p.accent,
    p.overlay, p.subtext, p.surface, p.green, p.surface, p.surface, p.surface,
    p.surface, p.surface, p.green, p.yellow, p.red, p.green, p.yellow, p.red,
    p.blue, p.accent, p.red, p.green, p.blue)
  writeFile("~/.config/btop/themes/omachy.theme", t)
  local conf = readFile("~/.config/btop/btop.conf")
  if conf and conf:match('color_theme%s*=') then
    writeFile("~/.config/btop/btop.conf",
      conf:gsub('color_theme%s*=%s*"[^"]*"', 'color_theme = "omachy"'))
  elseif not conf then
    writeFile("~/.config/btop/btop.conf",
      'color_theme = "omachy"\ntheme_background = False\ntruecolor = True\n')
  end
end

-- k9s: a generated skin + ui.skin pointer (config.yaml created if absent).
local function applyK9s(p)
  local skin = ([[# generated by hammerspoon/theme.lua — %s
k9s:
  body: { fgColor: "%s", bgColor: "default", logoColor: "%s" }
  prompt: { fgColor: "%s", bgColor: "%s", suggestColor: "%s" }
  info: { fgColor: "%s", sectionColor: "%s" }
  dialog:
    fgColor: "%s"
    bgColor: "default"
    buttonFgColor: "%s"
    buttonBgColor: "%s"
    buttonFocusFgColor: "%s"
    buttonFocusBgColor: "%s"
    labelFgColor: "%s"
    fieldFgColor: "%s"
  frame:
    border: { fgColor: "%s", focusColor: "%s" }
    menu: { fgColor: "%s", keyColor: "%s", numKeyColor: "%s" }
    crumbs: { fgColor: "%s", bgColor: "%s", activeColor: "%s" }
    status:
      newColor: "%s"
      modifyColor: "%s"
      addColor: "%s"
      errorColor: "%s"
      highlightColor: "%s"
      killColor: "%s"
      completedColor: "%s"
    title:
      fgColor: "%s"
      bgColor: "default"
      highlightColor: "%s"
      counterColor: "%s"
      filterColor: "%s"
  views:
    table:
      fgColor: "%s"
      bgColor: "default"
      header: { fgColor: "%s", bgColor: "default", sorterColor: "%s" }
    yaml: { keyColor: "%s", colonColor: "%s", valueColor: "%s" }
    logs: { fgColor: "%s", bgColor: "default" }
]]):format(p.name,
    p.text, p.accent, p.text, p.base, p.accent, p.accent, p.text,
    p.text, p.text, p.surface, p.base, p.accent, p.subtext, p.text,
    p.surface, p.accent, p.text, p.accent, p.yellow,
    p.subtext, p.base, p.accent,
    p.green, p.yellow, p.green, p.red, p.accent, p.red, p.blue,
    p.text, p.accent, p.accent, p.yellow,
    p.text, p.accent, p.accent, p.accent, p.subtext, p.text, p.subtext, p.text)
  writeFile("~/.config/k9s/skins/omachy.yaml", skin)
  -- Only patch an existing config.yaml — let k9s generate its own on first run
  -- (a hand-written stub trips its schema check on newer versions). Run k9s
  -- once, then switch theme again to wire `ui.skin`.
  local conf = readFile("~/.config/k9s/config.yaml")
  if conf and conf:match("skin:") then
    writeFile("~/.config/k9s/config.yaml", conf:gsub("skin:%s*[%w_-]*", "skin: omachy"))
  elseif conf and conf:match("\n  ui:") then
    writeFile("~/.config/k9s/config.yaml", conf:gsub("(\n  ui:\n)", "%1    skin: omachy\n", 1))
  end
end

-- nvim: LazyVim reads this name via lua/plugins/omachy-colorscheme.lua.
local function applyNvim(p)
  writeFile("~/.config/nvim/omachy-theme.txt", p.nvim .. "\n")
end

local function applyWallpaper(p)
  if not (M.setWallpaper and p.wallpaper) then return end
  local path = HOME .. "/Pictures/Wallpapers/" .. p.wallpaper
  if hs.fs.attributes(path) then
    hs.osascript.applescript(
      ('tell application "System Events" to tell every desktop to set picture to %q'):format(path))
  end
end

local function applyAppearance(p)
  if not M.setAppearance then return end
  hs.osascript.applescript(
    ('tell application "System Events" to tell appearance preferences to set dark mode to %s')
      :format(tostring(p.dark)))
end

-- ── change subscribers (Hammerspoon UI) ────────────────────────────────────
M._subs = {}
function M.onChange(fn) M._subs[#M._subs + 1] = fn end

local function applyHammerspoon(p)
  hs.alert.defaultStyle.fillColor   = { hex = p.mantle, alpha = 0.97 }
  hs.alert.defaultStyle.strokeColor = { hex = p.accent, alpha = 1 }
  hs.alert.defaultStyle.textColor   = { hex = p.text }
  hs.alert.defaultStyle.textFont    = "Hack Nerd Font Mono"
  hs.alert.defaultStyle.radius      = 0
  for _, fn in ipairs(M._subs) do pcall(fn, p) end
end

-- ── public API ─────────────────────────────────────────────────────────────
function M.current()
  return byName(settings.get(KEY) or "") or palettes[1]
end
M.colors = M.current            -- alias other modules use

function M.apply(name, opts)
  opts = opts or {}
  local p = byName(name) or M.current()
  local steps = {
    applyHammerspoon, applyBorders, applySketchybar, applyGhostty,
    applyBat, applyStarship, applyBtop, applyK9s, applyNvim,
  }
  if not opts.soft then                     -- skip on a plain reload
    steps[#steps + 1] = applyWallpaper
    steps[#steps + 1] = applyAppearance
  end
  for _, step in ipairs(steps) do
    local ok, err = pcall(step, p)
    if not ok then log.ef("apply %s: %s", p.name, err) end
  end
  return p
end

function M.set(name)
  local p = byName(name)
  if not p then hs.alert.show("theme: no '" .. tostring(name) .. "'"); return end
  settings.set(KEY, p.name)
  M.apply(p.name)
  hs.alert.show("  " .. p.label)
end

function M.cycle(dir)
  dir = dir or 1
  local cur = M.current().name
  local i = 1
  for idx, p in ipairs(palettes) do if p.name == cur then i = idx break end end
  local nxt = palettes[((i - 1 + dir) % #palettes) + 1]
  M.set(nxt.name)
end

-- rows for the Opt+Space menu: { name, action, marked }
function M.list()
  local cur = M.current().name
  local out = {}
  for _, p in ipairs(palettes) do
    out[#out + 1] = {
      name = p.label .. (p.name == cur and "   ✓" or ""),
      action = function() M.set(p.name) end,
    }
  end
  return out
end

return M
